# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 770041b8b2316ce0b6378a354d556ab7f9cac8f1aea92f2a0373a580764a9a134d9828dbf9dbd665bc4132c2afeecbc22b35f0e38266261420be2585f0224a26

test:
  secret_key_base: 3c7714cff130a70bba7f746ea3566e4ea3925c4de095ec70eb3dcf789433c7419701b170696e81245902334a559caee98e0e9d7ea9cb5d28d4aa8def19259587

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
